### ISSUE TITLE
WCHAR is not the same between Windows and Linux, how about typedef char16_t WCHAR?

### ISSUE THREAD

**Issue by lygstate** [microsoft/DirectX-Headers#114]
https://github.com/microsoft/DirectX-Headers/blob/48f23952bc08a6dce0727339c07cedbc4797356c/include/wsl/stubs/basetsd.h#L55C8-L55C8

That will makes it the same between Windows and Linux

**Comment by jenatali** [comment]
No. The intent is not ABI compatibility a-la WINE. WCHAR should be usable with C library wide char functions.
