### ISSUE TITLE
Request for the addition of the DirectStorage headers (dstorage.h/dstorageerr.h).

### ISSUE THREAD

**Issue by benvanik** [microsoft/DirectX-Headers#116]
It'd be great if the DirectStorage API headers were included in this repository and under the same license. Today they seem to only be available via nuget and the headers themselves aren't listed in `distributable_files.txt` so using them from git submodule dependencies (vs needing to use nuget) is tricky.

Specifically `native/include/dstorage.h` and `native/include/dstorageerr.h` from
https://nuget.info/packages/Microsoft.Direct3D.DirectStorage/1.2.2

**Comment by damyanp** [comment]
Hi!  The header files included in that package are licensed under the MIT license, as described by LICENSE-CODE.txt and the text at the beginning of those files.  This was explicitly set up this way to allow you to check the headers into source control.

The distributable_files.txt refers to the executable, binary code, that are covered by LICENSE.txt.

**Comment by benvanik** [comment]
Oh, neat! I hadn't noticed LICENSE-CODE.txt as covering those. Would still be cool to have them here so there's a one-stop submodule for users but this at least makes it easier to have our own submodule containing them.

**Comment by walbourn** [comment]
This issue should be taken to https://github.com/microsoft/DirectStorage rather than this repo which is focused on Direct3D 12 and related technologies.

**Comment by MarijnS95** [comment]
@walbourn in that case, does it make sense to (re)close this issue as "not planned", instead of "completed" to signify this?

![Image](https://github.com/user-attachments/assets/e881bcb7-a36e-4902-957c-8d19bf3e0867)
