### ISSUE TITLE
D3DX12.h Integration Instructions Not Clear

### ISSUE THREAD

**Issue by MadLights** [microsoft/DirectX-Headers#134]
Previously, you could just copy d3dx12.h into a project and be good to go.
It seems d3dx12.h has been split up into multiple files now, however simply copying the include/directx files to a project doesn't work.
Where are the instructions for using d3dx12.h for the new version?

**Comment by walbourn** [comment]
The choices here are:

* Use a package manager like VCPKG or NuGet to get these updated headers which includes the more modular D3DX12 library. See [directx-headers](https://github.com/microsoft/vcpkg/tree/master/ports/directx-headers) and [Microsoft.Direct3D.D3D12](https://www.nuget.org/packages/Microsoft.Direct3D.D3D12/)

* You can clone this repository as a sub-module into your project

* You can clone this repository and then copy it into your source tree

The headers here are under an MIT license to make all these options easier.

> Note that if you prefer the "single-file integration" approach, I maintain a modern copy [here](https://github.com/walbourn/directx-vs-templates/blob/main/d3d12game_win32_dr/d3dx12.h). It's mostly the same as the modular version except that all use of 'property tables' is not there as that requires at least a .cpp file.

**Comment by walbourn** [comment]
I'll file a doc PR against https://learn.microsoft.com/en-us/windows/win32/direct3d12/helper-structures-and-functions-for-d3d12 to get the integration instructions explicitly docd.

**Comment by walbourn** [comment]
https://github.com/MicrosoftDocs/win32/pull/1942
