### ISSUE TITLE
DxCore Fullscreen Swapchains

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/DirectX-Headers#16]
https://devblogs.microsoft.com/directx/directx-heart-linux/
> There is currently no presentation integration with WSL as WSL is a console only experience today. The D3D12 API can be used for offscreen rendering and compute, but there is no swapchain support to copy pixels directly to the screen (yet 😊).

Now that there is presentation integration with WSL would it be possible to add swapchains to DxCore for fullscreen use?

**Comment by jenatali** [comment]
First off, this isn't really the right repo for this kind of issue, it really belongs on https://github.com/microsoft/wslg. Second, we have no plans to add swapchains to DXCore, either for Windows or WSL. For Windows, apps should use DXGI swapchains or DComp. For WSL, apps need to integrate with X11 or Wayland, neither of which currently support consuming D3D resources, though this is something that we'll likely investigate in the future.
