### ISSUE TITLE
Clang warnings (as errors)

### ISSUE THREAD

**Issue by GlassBeaver** [microsoft/DirectX-Headers#29]
d3dx12.h(53,5): error : conversion function converting 'CD3DX12_RECT' to its base class 'tagRECT' will never be used [-Werror,-Wclass-conversion]

Getting several of these errors when compiling with Clang on Windows 10, as a workaround I've disabled them via `-Wno-class-conversion`.

**Comment by walbourn** [comment]
Actually I see the issue in the current version. Since it's publicly derived from ``D3D12_RECT``, this operator never gets used:

```
    explicit CD3DX12_RECT( const D3D12_RECT& o ) noexcept :
        D3D12_RECT( o )
    {}
```

I.e. it's already implicit with the fact that it's derived.

**Comment by walbourn** [comment]
I can't repro this with clang v12 using the C++11, C++14, or C++17 modes.

**Comment by walbourn** [comment]
I've tried some alternatives, but they don't build. I'm thinking in this case it may be a bug in the clang compiler. Which version are you using?

**Comment by GlassBeaver** [comment]
@walbourn Sorry I wasn't getting github notification emails for this issue. I remember using Clang 12 but couldn't tell you the exact version. FWIW I was compiling against C++20.

**Comment by walbourn** [comment]
I'm unable to reproduce this warning even with ``-Wall -Wpedantic -Wextra`` using clang v12. I tried C++11, C++14, C++17, C++20 modes.

**Comment by GlassBeaver** [comment]
Thanks for double checking, I suggest we close the issue and I'll report it again with more details should it resurface.
