### ISSUE TITLE
12_2 feature undeclared

### ISSUE THREAD

**Issue by r2com** [microsoft/DirectX-Headers#30]
During compilation it points to d3dx12.h with following error:
1>C:\projects\DirectX-Headers\include\directx\d3dx12.h(4822,9): error C2065: 'D3D_FEATURE_LEVEL_12_2': undeclared identifier

**Comment by r2com** [comment]
Alright, so updated today to a completely new MSVC, now I am running latest 2022 community and during setup I did install latest SDK's.

Now, during compile I do NOT get such error, i.e. it compiles without any issues. however, once I try to start executable, it fails with the following printout:
DX ERROR: D3D12CreateDevice: Unrecognized D3D_FEATURE_LEVEL (0xc200) for MinimumFeatureLevel. [ INITIALIZATION ERROR #506: ]
'dxtest5.exe' (Win32): Unloaded 'C:\Windows\System32\DXGIDebug.dll'

why is it still not recognizing feature of 12_2 with latest SDKs and even after successful compile?

**Comment by jenatali** [comment]
What Windows version are you running? You'll need to be on Win11 or using the Agility SDK for FL12.2 to be recognized.

**Comment by r2com** [comment]
well, here is a thing, I went to "Modify" section of MSVC installer, and it shows to me that I have Windows SDK 10.0.20348.0 installed.

For 12_2 I read that year ago, one needed 20170 or higher, it is obvious that my version is HIGHER than 20170 (20348), so it means it should have worked?

as per which windows, well, I am running Windows 10 Pro with above shown SDK. 

is that problem? are you saying that on top of version higher than 20170 I must also run Win11??

**Comment by walbourn** [comment]
You are building with the latest headers which define the ``D3D_FEATURE_LEVEL_12_2`` compiler symbol.

To actually *use* Feature Level 12.2, you need two things:

1. The DirectX 12 Runtime that supports Feature Level 12.2
2. A video driver & card combination that supports it.

The version of the DirectX 12 Runtime in Windows 11 supports Feature level 12.2.

For Windows 10 (18363) or later, you can use the [DirectX12 Agility SDK](https://aka.ms/directx12agility) and it provides an application local DLL version of the DirectX 12 Runtime that supports Feature Level 12.2 on your system.

**Comment by Esentiel** [comment]
I had the same issue with one object file where I compile shaders using dxc.
to resolve it I had to put `#include d3dx12.h ` above 
```
#include <dxc/dxcapi.h>
#include <dxc/d3d12shader.h>
```

Might be helpful for someone.
Cheers!
