### ISSUE TITLE
Can we get a new release that matches the header content to that provided in the v1.4.10 Agility SDK?

### ISSUE THREAD

**Issue by jlacroixAMD** [microsoft/DirectX-Headers#38]
The latest release dates back to the release of Agility SDK 1.4.9. 1.4.10 has since released and it would be nice to get a new release that matches that content.
Thanks.

**Comment by jenatali** [comment]
There were no header changes in 1.4.10, only a bugfix.

**Comment by jlacroixAMD** [comment]
Oh, that's excellent. Please disregard this request then. Thank you for the quick turnaround.
