### ISSUE TITLE
some headers are marked 'All rights reserved'

### ISSUE THREAD

**Issue by tjaalton** [microsoft/DirectX-Headers#4]
Hi

I've packaged this for Debian & Ubuntu, but the package got rejected by the archive admins due to some headers being marked with "© All rights reserved". This is considered to override the top-level LICENSE and as such makes the package not-distributable.

The headers are:
include/directx/{dxgiformat.h,d3d12shader.h,dxcore.h,dxgicommon.h,dxcore_interface.h,d3dx12.h}

**Comment by jenatali** [comment]
This is fixed with https://github.com/microsoft/DirectX-Headers/commit/73ed72b2afa617e605521eb740f77b4f7775c0df, which strips the "all rights reserved" text in favor of "licensed under the MIT license" text.
