### ISSUE TITLE
Tags corresponding to DX Agility SDK releases

### ISSUE THREAD

**Issue by vongkitt** [microsoft/DirectX-Headers#46]
There is one tag linking to DX Agility SDK 1.4.9 and 1.700.10 but not for the two other versions in-between (1.4.10, 1.600.10).
It would be helpful to have the tags that matches those releases on that page so we can match files like d3dx12.h to the SDK we are using.

https://devblogs.microsoft.com/directx/directx12agility/

**Comment by jenatali** [comment]
Yeah, I can push some more tags. 1.4.10 == 1.4.9 (no header changes, just bugfixes). Same with 1.600.10 == 1.700.10, same headers, just pre-release vs release.

**Comment by jenatali** [comment]
There you go, those should be the tags you're looking for.

**Comment by vongkitt** [comment]
Thank you, this helps a lot!
