### ISSUE TITLE
WSL2:  while compiling tests: C++ shared or static library 'd3d12' not found

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/DirectX-Headers#51]
While compiling DirectX-Headers with tests in WSL2 for the purpose of compiling Dozen ( Vulkan over DirectX12), I get `C++ shared or static library 'd3d12' not found`

![image](https://user-images.githubusercontent.com/49812372/164019380-5a2c3704-e37c-4d41-a5d5-e9d7c5c95f88.png)

libd3d12.so is clearly installed. 

Any suggestion how to make the tests to compile?

More background on this discussion is [here](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6318#note_1345241).

**Comment by jenatali** [comment]
Was this not fixed by #50?
