### ISSUE TITLE
1.606 D3DX12.H fails to build with MinGW and latest headers

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectX-Headers#72]
This new construct:

```
#if defined(_MSC_VER) || !defined(_WIN32)
        virtual D3D12_RESOURCE_DESC STDMETHODCALLTYPE GetDesc( void) = 0;
#else
        virtual D3D12_RESOURCE_DESC *STDMETHODCALLTYPE GetDesc( 
            D3D12_RESOURCE_DESC * RetVal) = 0;
#endif
```

Fails to build on MinGW. What is the purpose of this construction?

``_MSC_VER`` is set by MSVC, Intel, and clang/LLVM's cl-like front-end, but it's not set for MinGW.

Furthermore, the 'matching' D3DX12.H doesn't use this construct. so it also fails to build as well with MinGW:

```
D:/vcpkg/installed/x64-mingw-static/include/directx/d3dx12.h: In constructor 'CD3DX12_VIEWPORT::CD3DX12_VIEWPORT(ID3D12Resource*, UINT, FLOAT, FLOAT, FLOAT, FLOAT)':
D:/vcpkg/installed/x64-mingw-static/include/directx/d3dx12.h:79:45: error: no matching function for call to 'ID3D12Resource::GetDesc()'
   79 |         const auto Desc = pResource->GetDesc();
      |                           ~~~~~~~~~~~~~~~~~~^~

```

**Comment by jenatali** [comment]
Had you tried the MinGW builds at runtime before? It's my understanding that they were broken, due to not emulating MSVC's ABI quirk for C++ `stdcall` functions returning user-defined structs (#62, see also https://github.com/microsoft/DirectX-Graphics-Samples/issues/589#issuecomment-544785251 and https://devblogs.microsoft.com/oldnewthing/20220113-00/?p=106152).

For C callers that were previously compiling but not working, there was a workaround: since the functions in the vtable are just free functions, you could cast them to the correct signature and invoke them. But for C++ there's no equivalent workaround, so we adjusted the header to provide an "ABI" version of the function definitions for non-MSVC-identifying callers.

Good point that we missed updating `d3dx12.h` though.

**Comment by walbourn** [comment]
Fair enough.

There should be a way to opt in to the second ABI with MSVC like to avoid a lot of conditionals in client code.

Also some APIs in the video stuff is missing the _MSC_VER guard.

Finally we should see about getting Xbox to support the alt ABI.

**Comment by jenatali** [comment]
> There should be a way to opt in to the second ABI with MSVC like to avoid a lot of conditionals in client code.

Yeah, I'll see about adding that to MIDL.

> Also some APIs in the video stuff is missing the _MSC_VER guard.

That seems unlikely. This was code-generated by MIDL. Got an example?

> Finally we should see about getting Xbox to support the alt ABI.

That seems reasonable. Want to reach out to them and loop me in?

**Comment by walbourn** [comment]
There's quite a few cases of ``#if !defined(_WIN32)`` instead of ``#if defined(_MSC_VER) || !defined(_WIN32)`` in d3d12.h.

```
ID3D12DescriptorHeap::GetDesc
::GetCPUDescriptorHandleForHeapStart 
::GetGPUDescriptorHandleForHeapStart 
ID3D12CommandQueue::GetDesc
ID3D12Device::GetResourceAllocationInfo 
```

Look at the diff: https://github.com/microsoft/DirectX-Headers/compare/v1.602.0...v1.606.3

Is this ABI change supported by older versions of the Runtime, or only the Agility SDK version?

**Comment by jenatali** [comment]
Take a closer look at the `_WIN32` only definitions: they're for C. For C++, MSVC (and I believe Clang) have a quirk that causes them to *not* use small struct optimizations when returning user-defined structs from member functions. This causes the C interface to be incompatible, and also causes MinGW to target the wrong ABI for C++. We fixed the C interface a few years ago to match the actual ABI.

For WSL, no compiler has any such quirk. The C++ and C interface should both return structs. `libd3d12core.so` is built using C++, meaning that the WSL ABI was unaffected when we fixed the C header, and therefore WSL code is expecting struct returns.

There is no change to `D3D12Core.dll`'s or `libd3d12core.so`'s code from these definition updates, the only change is which compilers/languages/environments can successfully target them.

**Comment by walbourn** [comment]
I'll work on a PR to fix the D3DX12.H issues on MinGW then using this pattern:

```
#if defined(_MSC_VER) || !defined(_WIN32)
```

It would be helpful to determine what the future 'opt-in' preprocessor for the ALT-ABI would be for middleware and my libraries would be.

**Comment by walbourn** [comment]
Note these are the PRs to get my libraries building with these new headers for MinGW:

https://github.com/microsoft/DirectXTK12/pull/133

https://github.com/microsoft/DirectXTex/pull/279
