### ISSUE TITLE
Provide `.winmd` (win32metadata) files for the Agility SDK

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/DirectX-Headers#79]
In order to bind the most recent D3D12 Agility SDK in languages other than C, such as Rust, `.winmd` metadata files need to be generated for `windows-rs` to generate proper bindings. According to @mikebattista all the tooling exists and the repo just needs to build/provide them (I think based on `.idl` or `.h` files in this repo, by generating and publishing them as part of a GitHub release or inside the NuGet header package?): https://github.com/microsoft/win32metadata/issues/580#issuecomment-1301009333

**Comment by jenatali** [comment]
This sounds like goodness. I'm on-board as long as the maintenance cost isn't too high, and we can get instructions for how to set it up.

@mikebattista, sounds like you might be the person we need to work with to set this up? We can follow up internally if you prefer.

**Comment by MarijnS95** [comment]
@jenatali if at all possible I think it'd be great to integrate this with GitHub actions, so that you can essentially let the CI generate these without setting up any local environment, and it'd be accessible for anyone with push rights (also in forks) for convenience. These can also upload artifacts right to a release afaik.

Fwiw supposedly @riverar is the one tasked with writing documentation for this, and the one who's the most likely to help us out.

**Comment by MarijnS95** [comment]
Thanks, closing. Curious to see how quickly https://github.com/microsoft/DirectX-Headers/releases/tag/v1.610.0, which landed an hour ago, makes it into `win32metadata` and `windows-rs`. Is anyone having a notification trigger and/or responsibility for putting these releases through to `win32metadata` proactively?
