### ISSUE TITLE
[Agility SDK 1.608.2] missing header file D3D12TokenizedProgramFormat.hpp

### ISSUE THREAD

**Issue by Demonese** [microsoft/DirectX-Headers#86]
Source file `src\d3dx12\d3dx12_property_format_table.cpp` include header `D3D12TokenizedProgramFormat.hpp`, but the header does not exist.

Finally, I solved the problem by manually downloading the header files in this repository.

But I hope that similar rookie mistakes will not appear again, thanks.

**Comment by walbourn** [comment]
This has been fixed in newer Microsoft.Direct3D.D3D12 nuget packages.
