### ISSUE TITLE
D3DX12SerializeVersionedRootSignature desc_1_2 static sampler to desc_1_0

### ISSUE THREAD

**Issue by StarsX** [microsoft/DirectX-Headers#92]
For MaxVersion D3D_ROOT_SIGNATURE_VERSION_1_0 and pRootSignatureDesc->Version D3D_ROOT_SIGNATURE_VERSION_1_2, it seems D3D12_STATIC_SAMPLER_DESC1 has not been handled.

In D3DX12SerializeVersionedRootSignature of https://github.com/microsoft/DirectX-Headers/blob/main/include/directx/d3dx12_root_signature.h, starting from line 998:

D3D_ROOT_SIGNATURE_VERSION_1_1 and D3D_ROOT_SIGNATURE_VERSION_1_2 (line 1019) are the same path. However, root signature 1.2 includes D3D12_STATIC_SAMPLER_DESC1 for static non-normalized sampler. The current code only assigns the content of desc_1_1.pParameters into pParameters_1_0 for reconstructing a 1.0 signature when 1.1 is not supported. Meanwhile, desc_1_1.pStaticSamplers is directly assigned to CD3DX12_ROOT_SIGNATURE_DESC desc_1_0 (line 1089).

When pRootSignatureDesc->Version is D3D_ROOT_SIGNATURE_VERSION_1_1, desc_1_1.pStaticSamplers is identical to 1.0, which is safe to be reinterpreted as desc_1_0.pStaticSamplers . However, when pRootSignatureDesc->Version is D3D_ROOT_SIGNATURE_VERSION_1_2, desc_1_2 includes D3D12_STATIC_SAMPLER_DESC1 which is not compatible to desc_1_1. desc_1_2.pStaticSamplers should be handled to reconstruct pStaticSamplers_1_0.

I think the purpose of D3DX12SerializeVersionedRootSignature is to handle the compatibility of all root signature versions. Versions 1.2 is now exposed.

**Comment by jenatali** [comment]
Can you elaborate on what you mean by that?

**Comment by StarsX** [comment]
> Can you elaborate on what you mean by that?

I've added some explanations in detail. Hoping it is easy to understand for you.

**Comment by jenatali** [comment]
Ah, thanks, I missed the "X" in your original bug report and thought you were talking about the `D3D12SerializeVersionedRootSignature` API rather than the `D3DX12SerializeVersionedRootSignature` helper. Yes, I agree, this helper should be updated to correctly handle the static samplers from root signature 1.2 when running on a system that only supports root signature 1.0, at least for the cases that are possible to map back (e.g. no flags).

**Comment by jenatali** [comment]
Resolving as closed by #94

**Comment by StarsX** [comment]
> Resolving as closed by #94

Thanks. It is working for 1_2 to 1_0 now, but 1_2 to 1_1 (https://github.com/microsoft/DirectX-Headers/blob/main/include/directx/d3dx12_root_signature.h#L1147) still needs the similar fix.
